### PR TITLE
Commands are no longer CaSe-SeNsAtIvE which was a very annoying "issu…

### PR DESCRIPTION
**Pull request by juIio**
…e" with the current build of Factions

As you can see from this screenshot: http://prntscr.com/a81jag
I can perform Factions commands in any case and they will still run. (Take a look at /f show the other command is another thing that I added which is not in this branch).

### CODE REVIEW

**Comment by juIio** [comment]
Shoutout to @rbrick

**Comment by TheDiamondYT1** [comment]
:+1:

**Comment by gsand** [comment]
:+1:

**Comment by juIio** [comment]
@drtshock

**Pull request merged**
