### PR TITLE
Fix /f show

### PR DESCRIPTION
**Pull request by rbrick**

### CODE REVIEW

**Comment by drtshock** [comment]
What error is thrown here? Something about lang not having enough strings to replace.

**Comment by rbrick** [comment]
@drtshock If i recall correctly yes. I think it was a IllegalFormatException, i will post the error

**Comment by rbrick** [comment]
Error: http://paste.ubuntu.com/10553578/
f show: http://rbrickis.me/display.php?i=kPSlMdZmBPvpQyUT.png

**Comment by Miaourt** [comment]
+1 :3

**Comment by nsporillo** [comment]
:+1:

**Comment by Miaourt** [comment]
@drtshock ! :c

**Comment by Miaourt** [comment]
?.? @rbrick ?

**Pull request closed without merging**
