### PR TITLE
Remove Fanciful, fix compilation (part 1/2)

### PR DESCRIPTION
**Pull request by PaulBGD**
Currently compilation is broken because of
- Fanciful repository is down/broken
- EssentialsX constantly links to Essentials, which it then cannot find

This PR fixes the first issue. The second can be fixed by:
https://github.com/drtshock/Essentials/pull/36

This is not an optimal fix as it requires all users to be using Spigot. A better fix would be to add Fanciful to @drtshock's repository.

### CODE REVIEW

**Comment by blha303** [comment]
A fix that keeps compatibility with Bukkit would be preferable. I'll set up a repo with Essentials and Fanciful right now.

**Comment by blha303** [comment]
OK, well, I added fanciful to my repo at http://blha303.github.io/repo, but I can't build essentials because of the abovementioned error. Which is annoying. @drtshock can you help with this by making a PR to https://github.com/blha303/repo with the essentials jars? i can help with it if needed <3

**Comment by PaulBGD** [comment]
He's out for memorial weekend, but imo it'd be best to keep it inside his own repository as most of the other JARs are already in there. And since it's his own version of Essentials, I'd imagine he'd want those JARs in there too.

**Comment by blha303** [comment]
Well, I set up repo.drtshock,net for him, so I'll just add fanciful to there :P

edit: Or maybe I won't, because the ftp server is down.

**Comment by PaulBGD** [comment]
Well he's hosting his repo at https://ci.drtshock.net/plugin/repository/ now.

**Comment by blha303** [comment]
The problem with the Jenkins automatic maven repo is that it doesn't have any of the metadata that maven usually requires, which is why we make other repos to put artifacts into :/

**Comment by PaulBGD** [comment]
How does it not? He's already using it for EssentialsX.

**Comment by PaulBGD** [comment]
I'm actually surprised this got merged tbh

**Comment by drtshock** [comment]
It's only in a dev build. I want to see how this works as a way to do fancy messages as fanciful hasn't been the most reliable.

**Comment by PaulBGD** [comment]
Ah I see what you did.

**Comment by drtshock** [comment]
Yeah, didn't last long :c 
Reverted and put reason in commit https://github.com/drtshock/Factions/commit/de57060819b7dffb5a5a70d893a8b4bf29098d3b

**Pull request merged**
