### PR TITLE
Added a feature to enable or disable broadcasting tag changes

### PR DESCRIPTION
**Pull request by juIio**
This time it's a single PR haha. Sorry about the last one.

### CODE REVIEW

**Comment by drtshock** [comment]
Are we sure that's the only spot where tag changes are broadcasted?

**Comment by juIio** [comment]
I looked through the listeners package and the actual Event. It's definitely the only place. I also tested this in-game and it works as expected.

**Comment by juIio** [comment]
@drtshock ?

**Comment by drtshock** [comment]
:) thanks for contribution

**Comment by juIio** [comment]
No problem, glad to help!

**Pull request merged**
