### PR TITLE
/f delhome implementation

### PR DESCRIPTION
**Pull request by uf0h**
self explanatory ;D

### CODE REVIEW

**Comment by CmdrKittens** [comment]
Perhaps it could charge to do so, like setting the home does?

Not sure if it deserves a separate cost config or not.

**Comment by uf0h** [comment]
> 
> 
> Perhaps it could charge to do so, like setting the home does?
> 
> Not sure if it deserves a separate cost config or not.

I personally don't see a use case for charging players to remove their f home if you charge them to create it.

**Comment by CmdrKittens** [comment]
Isn't the use case for completely removing the home a strategic one?

**Comment by uf0h** [comment]
[0cffbe1](https://github.com/drtshock/Factions/pull/1271/commits/0cffbe1d15e7cdb3f6638ddc551e1b797cf92a61) fixes `/f sethome` cost

**Comment by CmdrKittens** [comment]
Thanks https://github.com/drtshock/Factions/commit/c97d74a7ef469413825b17a042bcfa1fa0cce755

**Pull request closed without merging**
