### PR TITLE
Fix formatting codes in description

### LINKED ISSUE #754: /f desc (Any player can input color).
/f desc (Any player can input color).

For example:

If player does /f desc &r &r&l

It makes his faction desc bold. This also works for colors, and other various things such as underline.
Would be appreciated if this can be fixed. Thanks

### PR DESCRIPTION
**Pull request by Kakifrucht**
Should close #754.

### CODE REVIEW

**Comment by CheatSupport** [comment]
Thanks, your the best. Please push this @drtshock and https://github.com/drtshock/Factions/pull/761

**Comment by drtshock** [comment]
I don't understand what the issue was

**Comment by CheatSupport** [comment]
This @drtshock https://github.com/drtshock/Factions/issues/754

**Comment by drtshock** [comment]
Yeah I don't understand the issue.

**Comment by Kakifrucht** [comment]
The color code filter for faction description did not check formatting codes (bold, italic, strikethrough etc.), only color codes.

**Pull request merged**
