### PR TITLE
Add short git hash to plugin.yml

### PR DESCRIPTION
**Pull request by animeavi**
I believe this will help with bug reports and it's nicer to have _something_ there at least.

### CODE REVIEW

**Comment by CmdrKittens** [comment]
But there *is* always something there - the actual build number off the CI server. 

This PR requires that the user has acquired it through `git` and not just downloaded source or copied source or anything else, *and* assumes they haven't made any uncommitted changes (at which point why not just download from the CI server).

Am I missing something or is this just for an edge case?

**Comment by animeavi** [comment]
Well not exactly an edge case, whenever I compile it myself it always says something like `1.6.9.5-U0.4.0-b${build.number}`, without actually adding anything there.

**Comment by animeavi** [comment]
I could try making it conditional.
If `${build.number}` is undefined perhaps?

**Comment by animeavi** [comment]
Ok, I've changed it now.
If you just use `mvn clean install` it will try to get the git hash.
If you define the build number with something like `mvn clean install -Dbuild.number=55` it will use that.

**Pull request closed without merging**
