### PR TITLE
Lower limit, and add first part to FancyMessage

### PR DESCRIPTION
**Pull request by Tibowl**
Whoops, didn't do enough testing xD

http://i.imgur.com/zIG2zOx.png Green part is where string got cut off.

### CODE REVIEW

**Comment by drtshock** [comment]
Please use an IDE for this and don't use tabs.

**Comment by Tibowl** [comment]
It's my autoformatter that uses tabs, changed it.

**Comment by drtshock** [comment]
Why do you need to set the fancy message to an empty string there?

**Comment by Tibowl** [comment]
Have you tried to use a .then without a first part? You will get an exeption.

**Comment by drtshock** [comment]
This was merged from another PR.

**Pull request closed without merging**
