### PR TITLE
Added more colors to parseColorTags, formatted more nicely

### PR DESCRIPTION
**Pull request by blha303**

### CODE REVIEW

**Comment by drtshock** [comment]
Reason for this? ;o Why can't we just use chat colors.

**Comment by blha303** [comment]
I thought it would be easier for translators / people adding custom strings to TL.yml

**Comment by drtshock** [comment]
We use &colorcode for that :)

**Comment by blha303** [comment]
Okay, cool, I meant to ask you which one you want so i can apply it to TL.

**Pull request closed without merging**
