### PR TITLE
Fix spaces with ", "

### LINKED ISSUE #134: /f show has no spaces
Screen shot explains all :)
Using build 136
http://i.imgur.com/nYzRGsb.png

### PR DESCRIPTION
**Pull request by Tibowl**
Fixes #134

### CODE REVIEW

**Comment by drtshock** [comment]
This solves part of the issue but there is also the issue of the string being too long for chat when factions have too many allies or enemies. Think you could tackle that one too? <3

**Comment by Tibowl** [comment]
There are 2 bugs that are left to fix:
- Colors get reset after a end of line, this can be fixed with coloring every letter of the Faction tag.
  <s>\- For me (idk about other users) the FancyMessage multiline's don't work, ex:
  - http://i.imgur.com/JGKfFMq.png
  - http://i.imgur.com/uThcx9e.png</s>

<s>I fixed that last one on a private plugin by using a custom FancyMessage class wich uses Items with lore for the multiple lines.</s> EDIT: 1.7.2 problem

**Comment by drtshock** [comment]
The multiline issue is just an issue with your line endings.

**Comment by Tibowl** [comment]
Did some testing, problem is in MineCraft 1.7.2 (vanilla, I play most of the time with basic mods), seems to be fixed in 1.8.

**Comment by drtshock** [comment]
I test everything in 1.7.10 right now and it worked fine. It's just your line endings or encoding.

**Comment by drtshock** [comment]
Thanks for the PR <3
I merged after formatting it.

**Comment by Tibowl** [comment]
Just did some testing today and saw that the clients sometimes still get kicked, I found out the reason that the FancyMessage's JSON is a little bit below the limit and then after one more ally/enemy it goes over the 32767 (2^16-1) limit of mc, because the code the next message will be put in a new message.

The 67 lenience is not really enough for this, you have the name + ', ' + tooltip.

This can be fixed by lowering the plugin limit by a bit, maybe for being extra cautious something in the 2000?

**Pull request merged**
