### PR TITLE
Massive overhaul tracking

### PR DESCRIPTION
**Pull request by CmdrKittens**
This is a work in progress, but should give a sign of what's been going on over the last few weeks.

* Permissions
  - [x] Perms are now the only way to control access between factions (#1128)
  - [x] Perms can be locked via config
  - [x] New GUI system for perms to match locking ability
     - [x] Remove any config reading for GUI for now, to be re-added in a later release
  - [x] Apply all perms to appropriate places in the code
  - [x] Add offline command/gui support
* Config
  - [x] New folder structure for configuration/data
  - [x] New configuration (with migration from old conf.json)
  - [x] New default perms (and offline perms) config
  - [x] Updated faction data for perms storage
  - [x] Automatic migration of all of the above
    - [x] Depositing old files into an oldConfig folder for backup/restore
  - [x] Test out some people's configs in migration to confirm nothing blows up
* Big incompletes
  - [x] warp sharing
  - [x] Fully separate out power-related functionality to its own config section
    - [x] Support choosing which raid-determination system is in play
      - [x] Implement Power option
    - [x] Migrate some scattered power configs to one place
  - [x] Add translations for anything presently hardcoded in this update
  - [x] Break just about all plugins by renaming critical classes and methods
    - [ ] Reach out to known plugins with update information prior to releasing on Spigot, giving time for them to update as well.

### CODE REVIEW

**Comment by instantout** [comment]
1: {offline-list} does not work.
2: Can claim over World Guard protected Regions.
3: /f Demote <player> does not auto-fill <player>
4: /f sethome needs a /f delhome, Since sometimes you get spawned killed. But, i don't think you
5: /f delwarp <warp> (does not autofill) guessing reasons.
Idea 1: Disable Fly when player hits water within faction. (Causes an advantage for Pvp).

"You dont have permission to null" error = You can't build. So Building is off limits even if its your own faction and your leader
PAINBUILD: So it works,  But /f perms does not help if you enable or disable it.

ITEM: 
So, idk what this is useful for but i believe it should be removed, any player should be able to use any item anywere Spawn eggs included.
TERRITORY:
/f Perms (Allowing to claim land), This lets you claim land if you're Recruit, but says you have to be a moderator to claim land.

**Comment by CmdrKittens** [comment]
Item 1, {offline-list} is resolved.
Item 2, worldguard, will check soon
Item 3-5 are not introduced by this branch, need separate tickets.
No permission to null, working on that, very weird.
Painbuild, will look into as well.
Item, if you don't like it, you just lock it down to enabled ;)
Territory issue, found the spots and will resolve soon.

**Comment by CmdrKittens** [comment]
Resolved:
* no permission to null
* territory permission still using mod status
* pressure plates murder players
* flower pots unprotected

remaining:
* worldguard claiming
* painbuild consistency

**Comment by CmdrKittens** [comment]
painbuild now actually allows build/destroy.

**Pull request merged**
