### PR TITLE
Fix maven, quick code cleanup

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
@drtshock Can we use this as temp workaround?

**Comment by drtshock** [comment]
@vemacs needs to give me access to the CI so I can setup the maven repo. Otherwise, I like everything there.

**Comment by drtshock** [comment]
Thanks for the contribution :)

**Comment by sgdc3** [comment]
Thank you ;) And please, keep updating the project! ;) P.S: any news about obsidiandestroyer?

**Comment by drtshock** [comment]
With my extreme limited time, I let Squid take that project over. Though it looks like he has about as much spare time as me :\

**Comment by sgdc3** [comment]
@drtshock Could you just fix the compatibility with the new API?

**Pull request merged**
