### PR TITLE
Beautifications

### PR DESCRIPTION
**Pull request by EthanJoyce**
- Remove outdated installation section.
- Remove the ugly "No player found" message when not handing the "kick" command any arguments.

### CODE REVIEW

**Comment by lol768** [comment]
I'm curious, what's outdated about the installation section? (The job exists)

**Comment by EthanJoyce** [comment]
@lol768 The job isn't public.

**Comment by lol768** [comment]
Sure. Still relevant to those who've purchased it though

**Comment by EthanJoyce** [comment]
@lol768 I believe that all the information is already available on the Spigot resource page. I would understand if that commit wasn't merged though.

**Comment by cnr** [comment]
We're going to keep the installation section as it is for now.

Pulled https://github.com/mrlolethan/Factions/commit/86c02ef2ce93fe65b8e222f0fa48443e42303f99 (`Remove ugly "No player found" message.`) as https://github.com/drtshock/Factions/commit/dc3e7e953b187ae661280fe64ae4d9a180edf114

Thanks for your contribution (:

**Pull request closed without merging**
