### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by Drc-DEV**
- CmdCoords readded
- Fixed some consistency issues in TL and some TODOs
- Added SuperVanish/PremiumVanish support and made a separate VanishUtil instead of defaulting to Essentials' Vanish ( not everybody uses essentials you know? ).
- Fixed nearby enemies check considering also vanished players ( which makes vanish useless )

### CODE REVIEW

**Comment by Drc-DEV** [comment]
@CmdrKittens any comment?

**Comment by CmdrKittens** [comment]
Was waiting until we shipped 0.5.8 first, before digging into it! Will check out soon. :)

**Comment by Drc-DEV** [comment]
I added a cancellable FPlayerTeleportEvent so that plugins that offer some kind of Combat Log protection can cancel the teleport if the player is in combat. This way there's no need to add internal hooks for CombatLog plugins.

**Comment by Drc-DEV** [comment]
@CmdrKittens ç_ç

**Comment by Drc-DEV** [comment]
I added a new config option to customize the default Role a player in a Faction should be put. Yes, Factions could already edit the default role, but as a server owner you may want to set for example the default role to "recruit" instead of "member", because most players assume that to be the default, and can't be bothered to change it.

**Comment by CmdrKittens** [comment]
Added in various items except the fall damage one. What case is caught by this addition that isn't caught by the existing listener?

**Comment by Drc-DEV** [comment]
> 
> 
> Added in various items except the fall damage one. What case is caught by this addition that isn't caught by the existing listener?

The case where the owner sets a no-fall-damage-time just below what is really needed.

**Comment by CmdrKittens** [comment]
> The case where the owner sets a no-fall-damage-time just below what is really needed.

Doesn't that mean they should just be updating their config?

**Comment by Drc-DEV** [comment]
> 
> 
> > The case where the owner sets a no-fall-damage-time just below what is really needed.
> 
> Doesn't that mean they should just be updating their config?

Sure, problem is the player still lost his stuff.

**Pull request closed without merging**
