### PR TITLE
Add /f stealth

### PR DESCRIPTION
**Pull request by dariasc**
idk if people actually want this. or if it's bloating it lol

### CODE REVIEW

**Review by WizzleBear — CHANGES_REQUESTED** [review]
Change the description by replacing "for" with "by".
Personally, I think this is a silly feature. If it's for staff, there are other alternatives. For players, this would be an OP feature.

**Comment by dariasc** [comment]
I mean admin bypassing does the job, it's just I saw a couple of issue requests for it. Might be a perk that can be gained, but yeah I agree it's quite op. Will fix typo

**Comment by dariasc** [comment]
Oh I think you misunderstand, stealth makes it so that other players nearby that are enemies don't get disabled by you.

**Comment by WizzleBear** [comment]
I did, sorry! I thought it made players not have their fly disabled by enemies.

**Comment by drtshock** [comment]
Seems super OP and is just like bypassing a key feature. Is this something people actually want?

**Comment by dariasc** [comment]
I saw two Issues asking for it, not sure if it's still something people want #1036 and #1054

**Comment by CmdrKittens** [comment]
After long deliberation, I am concluding the request is better served by an expanded `/f bypass`

**Pull request closed without merging**
