### PR TITLE
Config to disable Factions in worlds

### PR DESCRIPTION
**Pull request by animeavi**
I left the login/disconnect/kick events alone to not break anything.

### CODE REVIEW

**Comment by CmdrKittens** [comment]
Shuffled some things around. Still not ready. 

At a minimum, I think this needs to happen:

1. Only handling on-login things if in an enabled world. 
2. Tracking their state as they leave an enabled world (or join to a now-disabled world?)
3. Applying their state upon joining an enabled world.

**Comment by animeavi** [comment]
My thinking for not messing with on-login was "what if a players joins a Factions-disabled world then TPs to a Factions-enabled world"? Would that allow the player to bypass Factions stuff? I'm not too familiar with what the events do though.

**Comment by CmdrKittens** [comment]
Made an attempt at managing what I described above. I think it's ready for testing, but may also blow things up!

**Comment by CmdrKittens** [comment]
A testing jar has been posted to the MOSS discord in the #updates channel in the FactionsUUID category - https://discord.gg/PHpuzZS

**Comment by CmdrKittens** [comment]
Looking for review prior to merging. Updated test jar with this has been up for a bit today already in discord.

**Comment by CmdrKittens** [comment]
Thanks @animeavi :)

**Pull request merged**
