### PR TITLE
Make P.gson final

### PR DESCRIPTION
**Pull request by Techcable**
Before it could be null, triggering weird issues.

### CODE REVIEW

**Comment by CheatSupport** [comment]
This is legit.

**Comment by CheatSupport** [comment]
@drtshock can you add this? It's needed.

**Comment by Kakifrucht** [comment]
What issues does this fix?

**Comment by CheatSupport** [comment]
Fixes "FactionsTop" and a few other plugins that use this plugin. It's really needed @drtshock 

https://www.spigotmc.org/resources/factions-top-f-top-for-factionsuuid-massivecore-factions.16249/

**Comment by CheatSupport** [comment]
@drtshock Can you add this? It doesn't break anything. It fixes issues with other plugins

**Comment by Techcable** [comment]
@drtshock Is there anything I need to do to get this pulled?

**Comment by CheatSupport** [comment]
@drtshock oh my, how long will it take? cc: @vemacs @supaham

**Comment by SupaHam** [comment]
I have nothing to do with this project...

**Comment by vemacs** [comment]
1. Don't ping me, not a contributor
2. The more you bitch, the longer it takes

**Comment by CheatSupport** [comment]
@Kakifrucht Any news? Can you tell drtshock to merge?

**Comment by Kakifrucht** [comment]
Sorry, not a contributor either. Only person who can merge is @drtshock.

**Comment by CheatSupport** [comment]
Ok, no worries @Kakifrucht

**Comment by drtshock** [comment]
I'm curious what the issues were/are?

**Comment by Techcable** [comment]
Some other plugin was setting P.gson to null. This PR ensures it'll never happen again.

**Comment by vemacs** [comment]
If you reference the FPlayers class before Factions has loaded, the issue occurs as well. Not sure why.

**Comment by CheatSupport** [comment]
@drtshock can u seriously merge this?

**Comment by Techcable** [comment]
Yeah, it's probably that some other problem is referencing `FPlayers` before Factions loaded, not that it was setting it to null explicitly.
The reason it doesn't work is that `P.gson` used to be initialized in `preEnable`, and this moves it to the object's constructor.

**Comment by mattyokan** [comment]
@drtshock Would you be able to implement this to fix issues? It seems this is the cause of some peoples' player data & faction data not being saved.

**Comment by drtshock** [comment]
Looks like it should be merged.

**Pull request merged**
