### PR TITLE
Optimize MemoryBoard.

### PR DESCRIPTION
**Pull request by harrydevane**

### CODE REVIEW

**Comment by drtshock** [comment]
Give us some explanation of your commit?

**Comment by cnr** [comment]
At a cursory glance, this appears to reduce the complexity of retrieving the total chunks owned by a Faction. (to `O(1)` from `O(n)` where `n` is the number of chunks owned by all factions on the server)

Unfortunately, everything from the board is now stored _twice_ in memory, and the values (`Collection`s) held in `valueToKeyMap` are only accessed to determine their size. I'm not convinced this is the best way to approach it.

**Comment by harrydevane** [comment]
The reason for this change was due to a client of mine having tps issues with getFactionCoordCount().
It was using around 20% of the servers main thread alone.
https://www.harry5573.net/images/2015-08-26_14-47-14-uaLK1p24xEDT90k7QXvO.png

Yes, this approach uses double the memory, however it saves a ton of CPU.

**Comment by cnr** [comment]
Unless there's something I'm missing, I'd suggest storing `Integer`s as values in the inner `Map` instead of `Collection`s.

**Comment by harrydevane** [comment]
The reason for it being a collection is for the getAllKeys() method i added to optimize clean().

**Comment by TitanicFreak** [comment]
hmm, interesting. From my testing, the tradeoff is worth it, as well... we are now in an age were 16+GB minecraft instances are common.

**Comment by cnr** [comment]
Refactored to use `Multimap` instead of `Map` internally, and committed as https://github.com/drtshock/Factions/commit/0ede00f7df30f9ce94b6135dbf7730267f89a14d . Thanks!

**Comment by drtshock** [comment]
Thanks for the help :)

**Pull request closed without merging**
