### PR TITLE
Implement Faction Upgrades

### PR DESCRIPTION
**Pull request by dariasc**
Any opinions would be great.

The only thing left to do, is a bit of cleaning and UI implementation awaiting: #1194

### CODE REVIEW

**Comment by prosavage** [comment]
owo nice.

**Comment by jrodr10** [comment]
When will this be merged

**Comment by jrodr10** [comment]
hurry and merge this so i can fork it and port it to nukkit lol

**Comment by jrodr10** [comment]
merge this

**Comment by CmdrKittens** [comment]
@jrodr10 [commented](https://github.com/drtshock/Factions/pull/1196#issuecomment-557067827)

> merge this

Per the PR description it is incomplete. If you would like to complete it, we can get closer to merging it. :)

**Comment by jrodr10** [comment]
The PR description shows it as complete as the requirement for merge wrote in the description have already been fulfilled

**Comment by CmdrKittens** [comment]
@jrodr10 [commented](https://github.com/drtshock/Factions/pull/1196#issuecomment-557649937)

> The PR description shows it as complete as the requirement for merge wrote in the description have already been fulfilled

I will now quote the PR description:

> Any opinions would be great.
>
>The only thing left to do, is a bit of cleaning and UI implementation awaiting: #1194

I will now quote the PR content:

> `// TODO: Implement GUI`

I will now quote GitHub's merge warning:

> This branch has conflicts that must be resolved

And now, I quote myself:

> If you would like to complete it, we can get closer to merging it. :)

**Comment by jrodr10** [comment]
How much thought did you have to put into that comment lol 😂

**Comment by garbagemule** [comment]
@jrodr10 Infinitely more than you put into your contribution to the PR. Then again, who hasn't?

**Comment by jrodr10** [comment]
2 years later can this be merged

**Comment by Gabo6480** [comment]
What is this missing so it can be merged?

**Comment by mbax** [comment]
> What is this missing so it can be merged?

Just about everything. It needs a total rewrite at this point and only sits open for the sake of being a reminder. I'm going to close it because I still know it's here and can reference it when I need to.

**Pull request closed without merging**
