### PR TITLE
add API to ignore alliance chat

### PR DESCRIPTION
**Pull request by vemacs**
I'm not sure if you guys are fine with just an API pull request, but I don't feel comfortable enough with the codebase to make a command and such. This adds methods to prevent alliance chat from being shown to players.

### CODE REVIEW

**Comment by drtshock** [comment]
I'll commit this once I pull and add a command to utilize it. Thanks for another contribution :)

**Comment by vemacs** [comment]
Yeah, I was having issues deciding on the "permission" flags for the command framework. Was slightly confusing.

**Comment by vemacs** [comment]
I added the command, couldn't think of a better name. Pretty high demand for this from YouTubers.

**Comment by drtshock** [comment]
Thanks! I also added the permission to the plugin.yml, used a ternary, and added a new line after the class declaration and just amended that to your commit.

**Pull request merged**
